test pull
yaroslawv-nexus/sat-team-project pull request #6
Opened 2023-04-20 11:55 UTC by WaldemarYW

2023-04-20 11:56 UTC, yaroslawv-nexus requested changes
Повертаю)

2023-04-21 18:26 UTC, Ivanor1505 reviewed
Передивись будьласка розміри тексту і заголовка, порівняй з макетом.

2023-04-21 18:52 UTC, Ivanor1505 approved these changes

2023-04-21 18:55 UTC, yaroslawv-nexus approved these changes

2023-04-21 18:56 UTC, merged